swagger: '2.0'
info:
  title: Pi K8s Fitches Speech API
  version: "0.1"
consumes:
  - application/json
produces:
- application/json
paths:
  /health:
    get:
      operationId: service.health
      tags: [Health]
      summary: Health check
      responses:
        200:
          description: We're good
  /setting:
    get:
      operationId: service.setting_list
      tags: [Speak]
      summary: Settings for dealing with Speech
      responses:
        200:
          description: We're good
  /speak:
    post:
      operationId: service.speak
      tags: [Speak]
      summary: Speech to Text
      consumes:
        - application/json
      parameters:
        - in: body
          name: message
          description: The message playload
          schema:
            type: object
            required:
              - text
              - language
            properties:
              text:
                type: string
                description: The text to speak
              language:
                type: string
                description: The language to speak it in, ie 'en'
              node:
                type: string
                description: The node to speak it on (will do all nodes if missing)
      responses:
        202:
          description: Will be spoken
